INSERT INTO CITY (ID, NAME, COUNTRY) VALUES (1, 'MANILA', 'PHILIPPINES');
INSERT INTO CITY (ID, NAME, COUNTRY) VALUES (2, 'LONDON', 'UK');
INSERT INTO CITY (ID, NAME, COUNTRY) VALUES (3, 'NEW YORK', 'USA');
INSERT INTO CITY (ID, NAME, COUNTRY) VALUES (4, 'PARIS', 'FRANCE');